/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_630();
// int putchar(int c);
// int puts(const char *s);
// void *memset(void *s, int c, size_t n);
// __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD); weak
// int __fastcall _cxa_finalize(void *);
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
char *sub_6D0();
__int64 sub_710();
char *sub_760();
__int64 sub_7A0();
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_200D98)() = &sub_7A0; // weak
__int64 (__fastcall *off_200DA0)() = &sub_760; // weak
void *off_201008 = &off_201008; // idb
char asc_201020[830] = "-------------------------------------------------------------------[>[-]<[-]]>[>--------------------------------------------------------[>[-]<[-]]>[>-------------------------------------------------------[>[-]<[-]]>[>------------------------------------------------------[>[-]<[-]]>[>---------------------------------------------------[>[-]<[-]]>[>---------------------------------[>[-]<[-]]>[>>----[---->+<]>++.++++++++.++++++++++.>-[----->+<]>.+[--->++<]>+++.>-[--->+<]>-.[---->+++++<]>-.[-->+<]>---.[--->++<]>---.++[->+++<]>.+[-->+<]>+.[--->++<]>---.++[->+++<]>.+++.[--->+<]>----.[-->+<]>-----.[->++<]>+.-[---->+++<]>.--------.>-[--->+<]>.-[----->+<]>-.++++++++.--[----->+++<]>.+++.[--->+<]>-.-[-->+<]>---.++[--->+++++<]>.++++++++++++++.+++[->+++++<]>.[----->+<]>++.>-[----->+<]>.---[->++<]>-.++++++.[--->+<]>+++.+++.[-]]]]]]]"; // weak
char byte_201360; // weak
_BYTE array[400]; // idb


//----- (0000000000000618) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (__int64 (**)(void))_gmon_start__();
  return result;
}
// 201550: using guessed type __int64 _gmon_start__(void);

//----- (0000000000000630) ----------------------------------------------------
void sub_630()
{
  JUMPOUT(0LL);
}
// 636: control flows out of bounds to 0

//----- (00000000000006A0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  int v3; // [rsp-8h] [rbp-8h]
  __int64 _0; // [rsp+0h] [rbp+0h]

  v2 = v3;
  *(_QWORD *)&v3 = a1;
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    (char **)&_0,
    (void (*)(void))init,
    fini,
    a2,
    &v3);
  __halt();
}
// 6A6: positive sp value 8 has been found

//----- (00000000000006D0) ----------------------------------------------------
char *sub_6D0()
{
  char *result; // rax

  result = &byte_201360;
  if ( &byte_201360 != &byte_201360 )
  {
    result = (char *)&ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      result = (char *)ITM_deregisterTMCloneTable();
  }
  return result;
}
// 201360: using guessed type char byte_201360;
// 201548: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000000710) ----------------------------------------------------
__int64 sub_710()
{
  return 0LL;
}

//----- (0000000000000760) ----------------------------------------------------
char *sub_760()
{
  char *result; // rax

  if ( !byte_201360 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_201008);
    result = sub_6D0();
    byte_201360 = 1;
  }
  return result;
}
// 201360: using guessed type char byte_201360;

//----- (00000000000007A0) ----------------------------------------------------
__int64 sub_7A0()
{
  return sub_710();
}

//----- (00000000000007AA) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  int v4; // [rsp+8h] [rbp-28h]
  int v5; // [rsp+8h] [rbp-28h]
  int i; // [rsp+Ch] [rbp-24h]
  _BYTE *v7; // [rsp+10h] [rbp-20h]
  char *j; // [rsp+18h] [rbp-18h]
  int v9; // [rsp+22h] [rbp-Eh]
  __int16 v10; // [rsp+26h] [rbp-Ah]
  unsigned __int64 v11; // [rsp+28h] [rbp-8h]

  v11 = __readfsqword(40u);
  memset(array, 0, 0x190uLL);
  v7 = array;
  v9 = 0;
  v10 = 0;
  puts("Tell me a joke, if it's good enough, I'll show you the flag");
  __isoc99_scanf("%6s", &v9);
  for ( i = 0; i <= 5; ++i )
  {
    array[2 * i] = *((_BYTE *)&v9 + i);
    array[2 * i + 1] = 1;
  }
  for ( j = asc_201020; *j; ++j )
  {
    switch ( *j )
    {
      case 43:
        ++*v7;
        break;
      case 45:
        --*v7;
        break;
      case 46:
        putchar((char)*v7);
        break;
      case 60:
        --v7;
        break;
      case 62:
        ++v7;
        break;
      case 91:
        if ( !*v7 )
        {
          v4 = 1;
          while ( v4 > 0 )
          {
            if ( *++j == 91 )
            {
              ++v4;
            }
            else if ( *j == 93 )
            {
              --v4;
            }
          }
        }
        break;
      case 93:
        if ( *v7 )
        {
          v5 = 1;
          while ( v5 > 0 )
          {
            if ( *--j == 91 )
            {
              --v5;
            }
            else if ( *j == 93 )
            {
              ++v5;
            }
          }
        }
        break;
      default:
        continue;
    }
  }
  puts("\nNuh, idk, probably");
  return 0LL;
}
// 680: using guessed type __int64 __fastcall __isoc99_scanf(_QWORD, _QWORD);

//----- (00000000000009C0) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r15
  signed __int64 v4; // rbp
  __int64 i; // rbx

  v3 = a3;
  v4 = &off_200DA0 - &off_200D98;
  init_proc();
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&off_200D98 + i))(a1, a2, v3);
  }
}
// 200D98: using guessed type __int64 (__fastcall *off_200D98)();
// 200DA0: using guessed type __int64 (__fastcall *off_200DA0)();

//----- (0000000000000A34) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 10 function(s) have been successfully decompiled
